using SolidWorks.Interop.sldworks;

namespace SwAutomation;

public static class Project1
{
    public static void Run(string outFolder, Part part, Assembly assembly)
    {
        if (string.IsNullOrWhiteSpace(outFolder))
            throw new System.ArgumentException("Output folder is required.", nameof(outFolder));

        // 1) Create parts (names are generated by PDM save flow)
        string skeleton = part.CreateSkeleton(
            sideOffset: 500.0,
            groundOffset: -250.0,
            outFolder: outFolder,
            closeAfterCreate: true,
            SaveToPdm: true);

        // 2) Create assemblies (capture real vaulted file names)
        string rotor = assembly.CreateAssembly(outFolder, "RotorComplete.SLDASM", closeAfterCreate: true, SaveToPdm: true);
        string stator = assembly.CreateAssembly(outFolder, "StatorComplete.SLDASM", closeAfterCreate: true, SaveToPdm: true);
        string housing = assembly.CreateAssembly(outFolder, "HousingMachined.SLDASM", closeAfterCreate: true, SaveToPdm: true);
        string machine = assembly.CreateAssembly(outFolder, "MachineAssembly.SLDASM", closeAfterCreate: false, SaveToPdm: true);

        // 3) Insert and mate components into the open machine assembly
        Component2 inserted = assembly.InsertComponentToOpenAssembly(skeleton);
        assembly.mate_plans(inserted);

        inserted = assembly.InsertComponentToOpenAssembly(rotor);
        assembly.mate_plans(inserted);

        inserted = assembly.InsertComponentToOpenAssembly(stator);
        assembly.mate_plans(inserted);

        inserted = assembly.InsertComponentToOpenAssembly(housing);
        assembly.mate_plans(inserted);

        System.Console.WriteLine($"Macro completed. Machine assembly: {machine}");
    }
        public static void Run2(string outFolder, Part part, Assembly assembly)
    {
        if (string.IsNullOrWhiteSpace(outFolder))
            throw new System.ArgumentException("Output folder is required.", nameof(outFolder));

        // 1) Create parts (names are generated by PDM save flow)
        string skeleton = part.CreateSkeleton(
            sideOffset: 2000.0,
            groundOffset: -500.0,
            outFolder: outFolder,
            closeAfterCreate: true,
            SaveToPdm: false);

        string statorsheet = part.Create_stator_sheet(outFolder, true, SaveToPdm: false);
        string shaft = part.Create_shaft(outFolder, true, SaveToPdm: false);
        string machine = assembly.CreateAssembly(outFolder, "MachineAssembly.SLDASM", closeAfterCreate: false, SaveToPdm: false);

        Component2 inserted_skeleton = assembly.InsertComponentToOpenAssembly(skeleton);
        assembly.mate_plans(inserted_skeleton);
        Component2 inserted_statorsheet = assembly.InsertComponentToOpenAssembly(statorsheet);
        Component2 inserted_shaft = assembly.InsertComponentToOpenAssembly(shaft);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", inserted_statorsheet, "Z-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", inserted_statorsheet, "Ebene vorne");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", inserted_statorsheet, "Ebene rechts");
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", inserted_shaft, "Z-Achse");
        System.Console.WriteLine($"Macro completed. Machine assembly: {machine}");
    }
            public static void Run3(string outFolder, Part part, Assembly assembly)
    {
        if (string.IsNullOrWhiteSpace(outFolder))
            throw new System.ArgumentException("Output folder is required.", nameof(outFolder));

        //string statorsheet = part.Create_stator_distance_sheet(outFolder, false, SaveToPdm: false);
        //string statorend = part.Create_stator_end_sheet(outFolder, false, SaveToPdm: false);
        //string tensionbar = part.Create_tension_bar(outFolder, false, SaveToPdm: false);
        //string pressPlate = part.Create_press_plate(outFolder, false, SaveToPdm: false);
        //string pressRing = part.Create_stator_pressring_nde(outFolder, false, SaveToPdm: false);

    }
     public static void Run4(string outFolder, Part part, Assembly assembly)
    {
        if (string.IsNullOrWhiteSpace(outFolder))
            throw new System.ArgumentException("Output folder is required.", nameof(outFolder));

        double Mm(double mm) => mm / 1000.0;
        // Driving part dimensions mirrored from the part generators.
        double statorSheetThicknessMm = 100.0;                  // Part.Create_stator_sheet -> plateThicknessMm
        double statorDistanceSheetThicknessMm = 1.0;            // Part.Create_stator_distance_sheet -> plateThicknessMm
        double statorDistanceSheetFinHeightMm = 10.0;           // Part.Create_stator_distance_sheet -> bossExtrusionDepthMm
        double statorEndSheetThicknessMm = 1.0;                 // Part.Create_stator_end_sheet -> plateThicknessMm
        double pressPlateRingThicknessMm = 2.0;                 // Part.Create_press_plate -> ringThicknessMm
        double pressPlateBodyThicknessMm = 10.0;                // Part.Create_press_plate -> plateBodyThicknessMm
        double pressRingNdeThicknessMm = 28.0;                  // Part.Create_stator_pressring_nde -> ringThicknessMm
        double pressRingNdePocketCenterRadiusMm = 520.0;        // Part.Create_stator_pressring_nde -> pocketCenterRadiusMm
        int pressRingNdePocketCount = 8;                        // Part.Create_stator_pressring_nde -> pocketCount
        int repeatedDistanceEndSheetPacks = 5;
        double pressPlateAngleDeg = 3.0;

        // Derived assembly dimensions.
        double statorSheetPackThicknessMm = statorSheetThicknessMm;
        double statorDistanceSheetStackThicknessMm = statorDistanceSheetThicknessMm + statorDistanceSheetFinHeightMm;
        double statorEndSheetStackThicknessMm = statorEndSheetThicknessMm;
        double pressPlateStackThicknessMm =
            pressPlateBodyThicknessMm >= pressPlateRingThicknessMm ? pressPlateBodyThicknessMm : pressPlateRingThicknessMm;
        double pressRingNdeStackThicknessMm = pressRingNdeThicknessMm;
        double repeatedStackBlockThicknessMm = statorDistanceSheetStackThicknessMm + statorEndSheetStackThicknessMm + statorSheetPackThicknessMm;
        double torsionBarSlotRadiusMm = pressRingNdePocketCenterRadiusMm;
        int torsionBarPatternCount = pressRingNdePocketCount;

        // 1) Create parts (names are generated by PDM save flow)
        string skeleton = part.CreateSkeleton(
            sideOffset: 2000.0,
            groundOffset: -500.0,
            outFolder: outFolder,
            closeAfterCreate: true,
            SaveToPdm: false);

        string statorSheet = part.Create_stator_sheet(outFolder, false, SaveToPdm: false);
        string statorDistanceSheet = part.Create_stator_distance_sheet(outFolder, false, SaveToPdm: false);
        string statorEndSheet = part.Create_stator_end_sheet(outFolder, false, SaveToPdm: false);
        string tensionBar = part.Create_tension_bar(outFolder, false, SaveToPdm: false);
        string pressPlate = part.Create_press_plate(outFolder, false, SaveToPdm: false);
        string pressRingNde = part.Create_stator_pressring_nde(outFolder, false, SaveToPdm: false);
        string machine = assembly.CreateAssembly(outFolder, "MachineAssembly.SLDASM", closeAfterCreate: false, SaveToPdm: false);

        Component2 inserted_skeleton = assembly.InsertComponentToOpenAssembly(skeleton);
        assembly.mate_plans(inserted_skeleton);
        double stackOffsetMm = 0.0;
        Component2 insertedStackComponent;

        insertedStackComponent = assembly.InsertComponentToOpenAssembly(pressRingNde);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", insertedStackComponent, "Z-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", insertedStackComponent, "Ebene rechts");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", insertedStackComponent, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += pressRingNdeStackThicknessMm;

        insertedStackComponent = assembly.InsertComponentToOpenAssembly(pressPlate);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", insertedStackComponent, "Z-Achse");
        assembly.ApplyAngleMate(inserted_skeleton, "Ebene vorne", insertedStackComponent, "Ebene rechts", pressPlateAngleDeg);
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", insertedStackComponent, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += pressPlateStackThicknessMm;


        insertedStackComponent = assembly.InsertComponentToOpenAssembly(statorEndSheet);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", insertedStackComponent, "Z-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", insertedStackComponent, "Ebene rechts");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", insertedStackComponent, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += statorEndSheetStackThicknessMm;

        insertedStackComponent = assembly.InsertComponentToOpenAssembly(statorSheet);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", insertedStackComponent, "Z-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", insertedStackComponent, "Ebene rechts");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", insertedStackComponent, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += statorSheetPackThicknessMm;

        Component2 repeatedDistanceSeed = assembly.InsertComponentToOpenAssembly(statorDistanceSheet);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", repeatedDistanceSeed, "Z-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", repeatedDistanceSeed, "Ebene rechts");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", repeatedDistanceSeed, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += statorDistanceSheetStackThicknessMm;

        Component2 repeatedEndSeed = assembly.InsertComponentToOpenAssembly(statorEndSheet);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", repeatedEndSeed, "Z-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", repeatedEndSeed, "Ebene rechts");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", repeatedEndSeed, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += statorEndSheetStackThicknessMm;

        Component2 repeatedStatorSeed = assembly.InsertComponentToOpenAssembly(statorSheet);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", repeatedStatorSeed, "Z-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", repeatedStatorSeed, "Ebene rechts");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", repeatedStatorSeed, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += statorSheetPackThicknessMm;

        assembly.CreateLinearComponentPattern(
            inserted_skeleton,
            "X-Achse",
            repeatedDistanceEndSheetPacks + 1,
            Mm(repeatedStackBlockThicknessMm),
            repeatedDistanceSeed,
            repeatedEndSeed,
            repeatedStatorSeed);

        stackOffsetMm += repeatedDistanceEndSheetPacks * repeatedStackBlockThicknessMm;

        insertedStackComponent = assembly.InsertComponentToOpenAssembly(statorEndSheet);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", insertedStackComponent, "Z-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", insertedStackComponent, "Ebene rechts", 0, true);
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", insertedStackComponent, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += statorEndSheetStackThicknessMm;

        insertedStackComponent = assembly.InsertComponentToOpenAssembly(pressPlate);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", insertedStackComponent, "Z-Achse");
        assembly.ApplyAngleMate(inserted_skeleton, "Ebene vorne", insertedStackComponent, "Ebene rechts", pressPlateAngleDeg);
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", insertedStackComponent, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += pressPlateStackThicknessMm;

        insertedStackComponent = assembly.InsertComponentToOpenAssembly(pressRingNde);
        assembly.ApplyCoincedentMate(inserted_skeleton, "X-Achse", insertedStackComponent, "Z-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", insertedStackComponent, "Ebene rechts");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", insertedStackComponent, "Ebene vorne", Mm(stackOffsetMm));
        stackOffsetMm += pressRingNdeStackThicknessMm;

        double totalStackLengthMm = stackOffsetMm;
        Component2 insertedTorsionBar = assembly.InsertComponentToOpenAssembly(tensionBar);
        assembly.ApplyParallelMate(inserted_skeleton, "X-Achse", insertedTorsionBar, "X-Achse");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene vorne", insertedTorsionBar, "Ebene oben");
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene oben", insertedTorsionBar, "Ebene vorne", Mm(torsionBarSlotRadiusMm));
        assembly.ApplyCoincedentMate(inserted_skeleton, "Ebene rechts", insertedTorsionBar, "Ebene rechts", Mm(totalStackLengthMm / 2.0));
        assembly.CreateCircularComponentPattern(inserted_skeleton, "X-Achse", torsionBarPatternCount, 2 * System.Math.PI, insertedTorsionBar);
        System.Console.WriteLine($"Macro completed. Machine assembly: {machine}");
    }
}
