using SolidWorks.Interop.sldworks;

namespace SwAutomation;

public static class Project1
{
    public static void Run(string outFolder, Part part, Assembly assembly)
    {
        if (string.IsNullOrWhiteSpace(outFolder))
            throw new System.ArgumentException("Output folder is required.", nameof(outFolder));

        // 1) Create parts (names are generated by PDM save flow)
        string skeleton = part.CreateSkeleton(
            sideOffset: 500.0,
            groundOffset: -250.0,
            outFolder: outFolder,
            closeAfterCreate: true);

        // 2) Create assemblies (capture real vaulted file names)
        string rotor = assembly.CreateAssembly(outFolder, "RotorComplete.SLDASM", closeAfterCreate: true);
        string stator = assembly.CreateAssembly(outFolder, "StatorComplete.SLDASM", closeAfterCreate: true);
        string housing = assembly.CreateAssembly(outFolder, "HousingMachined.SLDASM", closeAfterCreate: true);
        string machine = assembly.CreateAssembly(outFolder, "MachineAssembly.SLDASM", closeAfterCreate: false);

        // 3) Insert and mate components into the open machine assembly
        Component2 inserted = assembly.InsertComponentToOpenAssembly(skeleton);
        assembly.mate_plans(inserted);

        inserted = assembly.InsertComponentToOpenAssembly(rotor);
        assembly.mate_plans(inserted);

        inserted = assembly.InsertComponentToOpenAssembly(stator);
        assembly.mate_plans(inserted);

        inserted = assembly.InsertComponentToOpenAssembly(housing);
        assembly.mate_plans(inserted);

        System.Console.WriteLine($"Macro completed. Machine assembly: {machine}");
    }
}
